trainer:
  batch_size: 64
  val_batch_size: 64
  test_batch_size: 64
  max_epochs: 100
  class_start: 20
  class_end: 29
  k_shot: 10
  freeze: False
  pretrain: True
  pretrained_path: "../pretext/_experiments/Rot_Predict_CVCNN/feature_net_epoch300"

optimizer:
  params:
    lr_encoder: 0.001
    lr_classifier: 0.001
    weight_decay: 0

iteration: 100

num_class: 10

dataset_root: "../../dataset/Lora/"
